version: '3'
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Iter123456
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    networks:
      - iternet

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: 'rabbitmqcontainer'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
    expose:
      - 5672
    networks:
      - iternet

  rabbitmq-service:
    build:
      context: .
      dockerfile: Iter.Subscriber\Dockerfile
      args:
        RABBITMQ_HOSTNAME: rabbitMQ
        RABBITMQ_PORT: 5672
        RABBITMQ_USERNAME: guest
        RABBITMQ_PASSWORD: guest
        EMAILSETTINGS_HOST: smtp.office365.com
        EMAILSETTINGS_PORT: 587
        EMAILSETTINGS_ENABLESSL: true
        EMAILSETTINGS_USERNAME: iter_travel@hotmail.com
        EMAILSETTINGS_PASSWORD: Iter_12345
    depends_on:
      - rabbitMQ
      - sql
    networks:
      - iternet

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Iter.Api\Dockerfile
      args:
        RABBITMQ_HOSTNAME: rabbitMQ
        RABBITMQ_PORT: 5672
        RABBITMQ_USERNAME: guest
        RABBITMQ_PASSWORD: guest
        EMAILSETTINGS_HOST: smtp.office365.com
        EMAILSETTINGS_PORT: 587
        EMAILSETTINGS_ENABLESSL: true
        EMAILSETTINGS_USERNAME: iter_travel@hotmail.com
        EMAILSETTINGS_PASSWORD: Iter_12345
    environment:
        - ConnectionStrings:AppDatabase=Server=sql,1433;Database=iter_docker7;User=sa;Password=Iter123456;TrustServerCertificate=True;ConnectRetryCount=0
    ports:
      - 8080:80
    networks:
      - iternet      
    depends_on:
      - sql

networks:
  iternet:
    driver: bridge
